### PR TITLE
Validate Post Form with Zod and Implement Server-Side Data Fetching

### PR DESCRIPTION
**Pull request by 47anjan**
### Description

This pull request addresses two main features:

1. **Form Validation with Zod**: 
   - Implemented Zod for form validation in the PostForm component using React Hook Form.
   - Added validation rules to ensure data integrity and user input accuracy.

2. **Server-Side Data Fetching on Posts Page**:
   - Modified the `Posts` page to fetch data from the server.
   - Utilized asynchronous functions to retrieve and display posts from the server.

### How to Test
1. Navigate to the Posts page and observe the server-side data fetching.
2. Visit the crate post page and test form validation with Zod.

### Checklist

- [x] Form validation using Zod implemented.
- [x] Server-side data fetching on the Posts page.
- [x] Code is documented and follows project coding guidelines.
- [x] Tests (if applicable) have been updated or added.

### CODE REVIEW

**Comment by danybeltran** [comment]
Hi @anjankarmakar10 
The PR looks awesome! For some reason, adding or deleting a post does not work in the preview of this PR.  

image

You can see that posts are actually being created/deleted if you go to the production website of this repo [here](https://nextjs-typescript-and-mongodb-psi.vercel.app/posts).


The main issue is that the current code in this PR is not refreshing the /posts page, which explains why the `/posts` page shows a cached version of the page that shows the posts that existed at the time of the production deployment.

Try using [revalitePath](https://nextjs.org/docs/app/api-reference/functions/revalidatePath), which should re-render the page cached in the server

Try using it after a post is added or deleted, like `revalidatePath('/posts')` (this does not work in components with the `"use client"` directive)

**Comment by 47anjan** [comment]
In my code its looks completely fine, you can check the Prisma schema, I updated the Prisma schema, 
```
model Post {
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  title     String
  date      DateTime
  content   String
  
//   createdAt DateTime @default(now())
//   updatedAt DateTime @updatedAt
}
```
TO 
```
model Post {
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  title     String
  date      DateTime @default(now())
  content   String
}
```

make sure you update the new Prisma schema to your database [please delete all old posts from your database before uptadate]

```
npx prisma db push
```


**Watch Video** [here ](https://app.screencastify.com/v2/watch/aA0ZZqSRdchBtCb4Ej34)

**Comment by danybeltran** [comment]
Is that recording from your local dev. environment http://localhost:3000?

If it is, it would explain why it does work in development but not in production

This is the preview deployment to this PR:

https://nextjs-typescript-and-mongodb-git-fork-anjan-b0e0c5-danybeltran.vercel.app/, try adding/deleting posts

Maybe it's something related to caching (?)

**Comment by 47anjan** [comment]
How can I access the code of this site https://nextjs-typescript-and-mongodb-git-fork-anjan-b0e0c5-danybeltran.vercel.app/posts?. I need to see this code repo

**Comment by danybeltran** [comment]
> How can I access the code of this site https://nextjs-typescript-and-mongodb-git-fork-anjan-b0e0c5-danybeltran.vercel.app/posts?. I need to see this code repo

That link is the preview deployment of this pull request, it means it has your changes.

**Comment by 47anjan** [comment]
Any error in vercel deployment?

**Comment by danybeltran** [comment]
> Any error in vercel deployment?

Hello, there are no errors in the vercel deployment.
The /posts page is not SSR, it's static:

image

That's why it does not change when adding/deleting posts


Try using one of these:

image


https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-functions

**Comment by 47anjan** [comment]
Yes, I noticed that I got the same issue on vercel, I am currently working on this problem.

**Comment by danybeltran** [comment]
> Yes, I noticed that I got the same issue on vercel, I am currently working on this problem.

Using a dynamic function inside a server component could work, something like:

```tsx
// app/posts/page.tsx
import { headers } from "next/headers"
// other imports

export default async function Posts() {
  headers() // Should mark route as dynamic
  const posts = await prisma.post.findMany({})

  return (
    <section>
```

**Comment by 47anjan** [comment]
I found the problem. prisma should be imported from the Prisma client, not the server.

**Comment by danybeltran** [comment]
> I found the problem. prisma should be imported from the Prisma client, not the server.

It should be imported from "server", in this case, "server" is an alias that refers to `server/index.ts`, there is an instance of Prisma client exported as `prisma` (to prevent unnecesary instances of PrismaClient, you can see it here in the examples repo of Nextjs: https://github.com/vercel/examples/blob/main/storage/postgres-prisma/lib/prisma.ts). In this case, the issue is related to the rendering. Using a dynamic function should work, 
 here  https://github.com/danybeltran/nextjs-typescript-and-mongodb/pull/11#issuecomment-1851237035

**Comment by danybeltran** [comment]
> I found the problem. prisma should be imported from the Prisma client, not the server.

The problem is not the prisma client, the page is still static, it's the rendering. Try https://github.com/danybeltran/nextjs-typescript-and-mongodb/pull/11#issuecomment-1851237035

image

**Comment by 47anjan** [comment]
I know this, I am not importing prisma directly from prisma/client i will make an instance of prisma client. [prisma-client](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices)

**Comment by danybeltran** [comment]
> I know this, I am not importing prisma directly from prisma/client i will make an instance of prisma client. [prisma-client](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices)

I understand. There is an instance of Prisma client inside server/intex.ts
It can be used like this:

```ts
import { prisma } from "server"
```

**Comment by 47anjan** [comment]
ok, I am checking 😃.

**Comment by 47anjan** [comment]
> > I know this, I am not importing prisma directly from prisma/client i will make an instance of prisma client. [prisma-client](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices)
> 
> I understand. There is an instance of Prisma client inside server/intex.ts It can be used like this:
> 
> ```ts
> import { prisma } from "server"
> ```

**Comment by 47anjan** [comment]
> > Any error in vercel deployment?
> 
> Hello, there are no errors in the vercel deployment. The /posts page is not SSR, it's static:
> 
> image
> 
> That's why it does not change when adding/deleting posts
> 
> Try using one of these:
> 
> image
> 
> https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-functions

The post page shouldn't be static it should be SSR

**Comment by danybeltran** [comment]
Thank you @anjankarmakar10 🚀!!

**Pull request merged**
